### ISSUE TITLE
Issue with srsRAN-e2: No cell specified in rr.conf

### ISSUE THREAD

**Issue by Ali78k** [openaicellular/oaic#74]
## Issue Description ##
I've built and run srsRAN master branch along with Open5Gs core. This paraphernalia working well. now, I'm deploying OAIC's srsRAN in order to integrate with O-RAN near-RT RIC (with Open5Gs core too) but when I  run srsenb, I face to this error: 
`Error: Invalid configuration - No cell specified in rr.conf.`
## Setup Details ##
There is a vm for 5G core and 5G RAN Managed Functions:
Ubunru 18.04
#vCPUs: 4
RAM: 16GB

Open5Gs as 5G core
srsRAN-e2 with ZMQ option as RAN Simulator
I tried master and srs_KPIMON_5G branches.
## Expected Behavior ##
As I configuered in ~/.config/srsran/rr.conf, there must be no enb and one gnb. please, see the last section.
## Actual Behaviour ##
```
me@myserver:~/.config/srsran$ sudo srsenb 
---  Software Radio Systems LTE eNodeB  ---

Couldn't open , trying /home/me/.config/srsran/enb.conf
Reading configuration file /home/me/.config/srsran/enb.conf...

Built in RelWithDebInfo mode using commit eee2bbf on branch srs_KPIMON_5G.

Error: Invalid configuration - No cell specified in rr.conf.
Error deriving EUTRA cell parameters
Error processing arguments.
```
## Steps to reproduce the problem ##
Here is some part of configuration files I used
Open5Gs Configs:
```
amf:
    sbi:
      - addr: 127.0.0.5
        port: 7777
    ngap:
      - addr: 127.0.0.2
    metrics:
      addr: 127.0.0.5
      port: 9090
    guami:
      - plmn_id:
          mcc: 901
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 901
          mnc: 70
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 901
          mnc: 70
        s_nssai:
          - sst: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0

sgwu:
    pfcp:
      - addr: 127.0.0.6
    gtpu:
      - addr: 127.0.0.6

upf:
    pfcp:
      - addr: 127.0.0.7
    gtpu:
      - addr: 127.0.0.2
    subnet:
      - addr: 10.45.0.1/16
      - addr: 2001:db8:cafe::1/48
    metrics:
      - addr: 127.0.0.7
        port: 9090
```

enb.conf:

```
[enb]
enb_id = 0x19B
mcc = 901
mnc = 70
mme_addr = 127.0.0.2
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
s1c_bind_port = 0
n_prb = 50

[rf]
#dl_earfcn = 3350
tx_gain = 80
rx_gain = 40

device_name = zmq
device_args = fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=11.52e6

```
rr.conf:

```

cell_list =
(
);
nr_cell_list =
(
   {
    rf_port = 1;
    cell_id = 0x02;
    tac = 0x0007;
    pci = 500;
    root_seq_idx = 204;

    // TDD:
    //dl_arfcn = 634240;
    //band = 78;

    // FDD:
    dl_arfcn = 368500;
    band = 3;
    coreset0_idx = 6;
  }
);

```
